### ISSUE TITLE
Playtime hours Does not reset after 24 hours and show total hours.

### ISSUE THREAD

**Issue by agamsol** [PlaceholderAPI/Statistics-Expansion#23] opened 2020-12-15 08:55 UTC
`%statistic_time_played%`
The Seconds Works Fine also Minutes and days
But the Hours messing it up, when i play my server with the total time in the scoreboard
 it shows that i played 31 hours
and 1 day, but the day was added at 24 hours, but the hours were supposed to reset back to 0

please fix this issue as soon as possible, Thanks 😄

**Comment by darbyjack** [comment] 2020-12-15 09:05
Duplicate of #20 .

**Closed as completed by darbyjack** 2020-12-15 09:05 UTC
